openapi: "3.0.1"
info:
  title: "NotesAPI"
  version: "2025-11-19 09:46:03UTC"
servers:
- url: "https://mqu0t9cz6c.execute-api.eu-central-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: ""
paths:
  /notes/{id}:
    get:
      responses:
        default:
          description: "Default response for GET /notes/{id}"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:968960483877:function:NotesAPI/invocations"
        connectionType: "INTERNET"
    put:
      responses:
        default:
          description: "Default response for PUT /notes/{id}"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:968960483877:function:NotesAPI/invocations"
        connectionType: "INTERNET"
    delete:
      responses:
        default:
          description: "Default response for DELETE /notes/{id}"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:968960483877:function:NotesAPI/invocations"
        connectionType: "INTERNET"
    parameters:
    - name: "id"
      in: "path"
      description: "Generated path parameter for id"
      required: true
      schema:
        type: "string"
  /notes:
    get:
      responses:
        default:
          description: "Default response for GET /notes"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:968960483877:function:NotesAPI/invocations"
        connectionType: "INTERNET"
    post:
      responses:
        default:
          description: "Default response for POST /notes"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:968960483877:function:NotesAPI/invocations"
        connectionType: "INTERNET"
x-amazon-apigateway-importexport-version: "1.0"
